## These functions function as a pair to cache the inverse of a matrix 
## to avoid having to compute it repeatedly to save time and system 
## resources.

## This first function, 'makeCacheMatrix,' creates a matrix object 
## that can cache its inverse by the following process:
## 1.  set the value of the matrix
## 2.  get the value of the matrix
## 3.  set the value of the inverse of the matrix
## 4.  get the value of the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
	inv <- NULL
	set <-function(y) {
		x <<- y
		inv <<- NULL
	}
	get <- function() x
	setinverse <- function(inverse) inv <<- inverse
	getinverse <- function() inv
	list(set = set, get = get,
		setinverse = setinverse,
		getinverse = getinverse)

}

## This second function, 'cacheSolve,' calculates the inverse of the 
## matrix generated by the above function. First it tries pulling it 
## from cache if it's already been calculated. If not, it runs the 
## calculation and then stores it in cache.

cacheSolve <- function(x, ...) {
	inv <- x$getinverse()
    if(!is.null(inv)) {
           message("getting cached data")
           return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinverse(inv)
    inv
}